# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_auto_20161210_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Role')),
            ],
        ),
    ]
