language: python

python:
  - "2.7"
  
addons:
  firefox: "45.0"  
  
install:     
    - "pip install -r requirements.txt"
  
script: 
    - "cd TicketsRes;python manage.py test"
    - "coverage run manage.py test"
    - "cd AutomaticTests;pybot --pythonpath autolib --outputdir log --consolemarkers on TestSets/DjangoTestsSet.txt"
    
after_success:    
    - coveralls