language: python

python:
  - "2.7"
  
addons:
  firefox: "39.0"  
  
install:     
    - "pip install -r requirements.txt"
    
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "cd TicketsRes;python manage.py runserver &"
  
script: 
    - "python manage.py test"
    - "coverage run manage.py test"
    - "cd AutomaticTests;pybot --pythonpath autolib --outputdir log --consolemarkers on TestSets/DjangoTestsSet.txt"
    
after_success:    
    - coveralls