language: python

python:
  - "2.7"

sudo: 
    required
  
addons:
    firefox: "45.0"  

before_install:
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"
    #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x32"
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x32"
    - sleep 3 # give xvfb some time to start
    
  
install:     
    - "pip install -r requirements.txt"
    
before_script:
  - "cd TicketsRes;python manage.py runserver &"
  
script: 
    - "python manage.py test"
    - "coverage run manage.py test"
    - "cd AutomaticTests;pybot --pythonpath autolib --outputdir log --consolemarkers on TestSets/DjangoTestsSet.txt"
    
after_success:    
    - coveralls