language: python

python:
  - "2.7"

sudo: 
    required
  
addons:
    firefox: "50.1"  

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
  
install:     
    - "pip install -r requirements.txt"
    
before_script:
  - "cd TicketsRes;python manage.py runserver &"
  
script: 
    - "python manage.py test"
    - "coverage run manage.py test"
    - "cd AutomaticTests;pybot --pythonpath autolib --outputdir log --consolemarkers on TestSets/DjangoTestsSet.txt"
    
after_success:    
    - coveralls