language: python

python:
  - "2.7"
  
# command to install dependencies
install:    "pip install -q Django --use-mirrors"     

# command to run tests
script: "cd TicketsRes;python manage.py test TicketsReservation/"