# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventCreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField()),
                ('row', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guest_name', models.CharField(max_length=32)),
                ('guest_surname', models.CharField(max_length=32)),
                ('guest_email', models.CharField(max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.Event')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.Sector')),
            ],
        ),
    ]
