# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 23:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsReservation', '0003_tickets_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='column',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
